use_frameworks!

target 'Raptor_Example' do
  platform :ios, '13.0'
  pod 'Raptor', :path => '../'
  pod 'Base58String', :git => 'https://github.com/keefertaylor/Base58String.git'  
  
  target 'Raptor_Tests' do
    inherit! :search_paths

    
  end
end
